[package]
name = "digest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
sha1 = "*"
sha2 = "*"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"

